---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream10
dependencies:
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.18.8
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: awx.awx
      - name: azure.azcollection
        version: ">=2.1.0"
      - name: amazon.aws
      - name: theforeman.foreman
      - name: google.cloud
      - name: openstack.cloud
      - name: community.vmware
      - name: ovirt.ovirt
      - name: kubernetes.core
      - name: ansible.posix
      - name: ansible.windows
      - name: redhatinsights.insights
      - name: kubevirt.core
  system: |
    curl [platform:rpm]
    git-core [platform:rpm]
    python3.12-devel [platform:rpm]
    libcurl-devel [platform:rpm]
    krb5-devel [platform:rpm]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    unzip [platform:rpm]
    podman-remote [platform:rpm]
    cmake [platform:rpm]
    gcc [platform:rpm]
    gcc-c++ [platform:rpm]
    make [platform:rpm]
    openssl-devel [platform:rpm]
    grub2-tools-minimal [platform:rpm]
    openssl [platform:rpm]
    gcc [platform:rpm]
    openldap-devel [platform:rpm]
    butane [platform:rpm]
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    receptorctl
    pynetbox
    netaddr
    pexpect
    py-pure-client
    purestorage
    dnspython
    python-ldap
    passlib
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    - RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && chmod +x get_helm.sh && ./get_helm.sh && curl -fsSL -o /usr/local/bin/kubeadm https://dl.k8s.io/release/v1.29.3/bin/linux/amd64/kubeadm && chmod +x /usr/local/bin/kubeadm